#### Understanding  multiple regression coefficient from simple regression coefficient
#### Here we do a very simple linear regression test. 
#### (1) Generate Y = b1* X1 + b2* X2 + e, with X1 and X2 weakly correlated with each other (with corr = rho) 
#### (2) Regress X2~X1, take the residual X2 - X2^hat (X2 adjusted for X1)
#### (3) Then regress Y~ (X2-X2^hat). We'll get a coefficient the same as the multiple regression X2 coefficient for Y~(X1,X2):

The Multiple Regression coefficient for a certain variable, can be understood as the 'simple regression coefficient' after it's adjusted for other variables.

In [12]:
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
# Parameters

n_samples = 1000  # number of samples
a = 5
b1 = 3
b2 = 2

# Generate X1 and X2
np.random.seed(42)  # for reproducibility
X1 = np.random.rand(n_samples)
# print(X1)
np.random.seed(43)  # for reproducibility
X2 = np.random.rand(n_samples)
print(np.corrcoef(X1,X2))

# Make X1 and X2 correlated by rho
rho = 0.15
X2 = rho*X1 + np.sqrt(1-rho**2)*X2
print(np.corrcoef(X1,X2))

# Generate random error e
e = np.random.randn(n)

# Generate Y
Y = a + b1 * X1 + b2 * X2 + e

# Step 1: Dataset
Y[:5], X1[:5], X2[:5]  # Display first 5 entries for verification

[[ 1.         -0.00460955]
 [-0.00460955  1.        ]]
[[1.         0.14678641]
 [0.14678641 1.        ]]


(array([5.44185482, 9.39478548, 9.46328378, 6.99507966, 8.03178921]),
 array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864]),
 array([0.16993386, 0.7447827 , 0.24168087, 0.32766636, 0.3468406 ]))

In [19]:
# check linear regression 
def get_beta(Y,X):
    if(X.ndim == 1):
        X = X.reshape(-1,1)
    reg = LinearRegression().fit(X,Y)
    return reg.coef_, reg.predict(X)
# def get_yhat(Y,X):

beta_y_x1, yhat = get_beta(Y,X1)
y_x1 = Y-yhat # Y removing X1
print('beta_y_x1',beta_y_x1)
beta_x2_x1, x2hat = get_beta(X2,X1)
x2_x1 = X2-x2hat
print('beta_x2_x1',beta_x2_x1)
beta_yx1_x2x1, _ = get_beta(y_x1, x2_x1)
print('beta_yx1_x2x1', beta_yx1_x2x1)

beta_y_x2x1, _ = get_beta(Y, x2_x1)
print('beta_y_x2x1',beta_y_x2x1)

combined = np.column_stack((X1,X2))
coef, _ = get_beta(Y, combined)
print('coef', coef)

beta_x1_x2x1, _ = get_beta(X1, x2_x1)
print('beta_x1_x2x1',beta_x1_x2x1)

beta_y_x1 [3.23328107]
beta_x2_x1 [0.14548088]
beta_yx1_x2x1 [1.97208854]
beta_y_x2x1 [1.97208854]
coef [2.94637989 1.97208854]
beta_x1_x2x1 [7.97193061e-17]
